name: Deploy Full Stack

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"

      - name: Install dependencies (Root)
        run: yarn install

      - name: Build Todo Form
        run: |
          cd frontend/todo-form
          yarn build

      - name: Build Todo List
        run: |
          cd frontend/todo-list
          yarn build

      - name: Build Host
        run: |
          cd frontend/host
          yarn build
        env:
          VITE_FORM_URL: ${{ vars.VITE_FORM_URL }}
          VITE_LIST_URL: ${{ vars.VITE_LIST_URL }}
          VITE_API_URL: ${{ vars.VITE_API_URL }}
          VITE_USER_POOL_ID: ${{ vars.VITE_USER_POOL_ID }}
          VITE_USER_POOL_CLIENT_ID: ${{ vars.VITE_USER_POOL_CLIENT_ID }}

      - name: Deploy AWS CDK
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: CDK Deploy
        run: |
          cd infrastructure
          npx aws-cdk deploy --all --require-approval never
